import { useNavigate } from 'react-router-dom'
import { ArrowRight, BookOpen, CalendarDays, ClipboardCheck, GraduationCap, Users } from 'lucide-react'
import PageLayout from '../components/PageLayout'

const tools = [{ label: 'Teachers', description: 'Faculty and subject assignments', icon: GraduationCap, path: '/teachers' }, { label: 'Students', description: 'Profiles, enrollment and records', icon: Users, path: '/students' }, { label: 'Attendance', description: 'Daily marking and history', icon: ClipboardCheck, path: '/attendance' }, { label: 'Exams & Results', description: 'Assessments, marks and grades', icon: BookOpen, path: '/exams-results' }, { label: 'Timetable', description: 'Weekly class schedule', icon: CalendarDays, path: '/timetable' }]

export default function ClassDetail() {
  const navigate = useNavigate()
  return <PageLayout title="Class 1-A" subtitle="Academic Year 2026-27 · Room A-101" action={<span className="px-4 py-2 rounded-full text-xs font-bold" style={{ background: '#ecfdf5', color: '#059669' }}>Active Class</span>}><div className="rounded-2xl p-7 text-white mb-6" style={{ background: 'linear-gradient(120deg, #1e3a8a, #2563eb)' }}><div className="text-xs uppercase opacity-70 mb-2">Class overview</div><div className="text-3xl font-bold" style={{ fontFamily: 'Syne,sans-serif' }}>Class 1-A</div><div className="mt-2 text-sm opacity-80">12 students · 1 teacher · 40 seat capacity</div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-7">{[['Total Students', '12'], ['Total Teachers', '1'], ["Today's Attendance", '95.8%'], ['Pending Fees', 'PKR 0']].map(([label, value]) => <div key={label} className="bg-white rounded-2xl border p-5" style={{ borderColor: '#e2e8f0' }}><div className="text-sm" style={{ color: '#64748b' }}>{label}</div><div className="font-bold text-2xl mt-3" style={{ fontFamily: 'Syne,sans-serif' }}>{value}</div></div>)}</div><h3 className="font-bold text-xl mb-1" style={{ fontFamily: 'Syne,sans-serif' }}>Class Management</h3><p className="text-sm mb-4" style={{ color: '#64748b' }}>Everything you need to manage Class 1-A</p><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">{tools.map(tool => { const Icon = tool.icon; return <button key={tool.label} onClick={() => navigate(tool.path)} className="bg-white rounded-2xl border p-5 text-left hover:-translate-y-1 transition-transform" style={{ borderColor: '#e2e8f0' }}><div className="w-11 h-11 rounded-xl flex items-center justify-center mb-5" style={{ background: '#eef2ff', color: '#4f46e5' }}><Icon size={21} /></div><div className="font-bold">{tool.label}</div><div className="text-xs mt-2" style={{ color: '#94a3b8' }}>{tool.description}</div><ArrowRight size={16} className="mt-4" style={{ color: '#4f46e5' }} /></button> })}</div></PageLayout>
}