import { useEffect, useState } from 'react'
import { Pencil, Plus, Search, Trash2 } from 'lucide-react'
import axios from 'axios'
import PageLayout from '../components/PageLayout'
import API_BASE_URL from '../config/api'

const blank = { name: '', code: '', description: '', status: 'Active' }

export default function Subjects() {
  const schoolId = localStorage.getItem('schoolId')
  const [subjects, setSubjects] = useState([])
  const [form, setForm] = useState(blank)
  const [editing, setEditing] = useState(null)
  const [search, setSearch] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)

  const loadSubjects = async () => {
    try { setLoading(true); const response = await axios.get(`${API_BASE_URL}/subjects/${schoolId}`); setSubjects(response.data) } catch (loadError) { setError(loadError.response?.data?.error || 'Unable to load subjects.') } finally { setLoading(false) }
  }

  useEffect(() => { if (schoolId) loadSubjects(); else { setError('School information not found. Please login again.'); setLoading(false) } }, [schoolId])
  const openForm = subject => { setEditing(subject || null); setForm(subject ? { name: subject.name, code: subject.code, description: subject.description || '', status: subject.status } : blank); setError('') }
  const saveSubject = async event => { event.preventDefault(); try { const response = editing ? await axios.patch(`${API_BASE_URL}/subjects/${editing._id}`, form) : await axios.post(`${API_BASE_URL}/subjects`, { ...form, schoolId }); setSubjects(current => editing ? current.map(subject => subject._id === editing._id ? response.data : subject) : [response.data, ...current]); setEditing(null) } catch (saveError) { setError(saveError.response?.data?.error || 'Unable to save subject.') } }
  const deleteSubject = async id => { try { await axios.delete(`${API_BASE_URL}/subjects/${id}`); setSubjects(current => current.filter(subject => subject._id !== id)) } catch (deleteError) { setError(deleteError.response?.data?.error || 'Unable to delete subject.') } }
  const visible = subjects.filter(subject => `${subject.name} ${subject.code}`.toLowerCase().includes(search.toLowerCase()))

  return <PageLayout title="Subjects" subtitle="Organize the curriculum and connect subjects to classes and teachers." action={<button onClick={() => openForm()} className="flex items-center gap-2 px-4 py-3 rounded-xl text-white text-sm font-bold" style={{ background: '#4f46e5' }}><Plus size={17} /> Add Subject</button>}>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">{[['Active Subjects', subjects.filter(subject => subject.status === 'Active').length], ['Teacher Links', 0], ['Class Assignments', 0]].map(([label, value]) => <div key={label} className="bg-white rounded-2xl border p-5" style={{ borderColor: '#e2e8f0' }}><div className="text-sm" style={{ color: '#64748b' }}>{label}</div><div className="font-bold text-2xl mt-3">{value}</div><div className="text-xs mt-1" style={{ color: '#10b981' }}>Live database total</div></div>)}</div>
    <div className="bg-white rounded-2xl border overflow-hidden" style={{ borderColor: '#e2e8f0' }}><div className="p-4 flex items-center gap-3 border-b" style={{ borderColor: '#e2e8f0' }}><Search size={17} style={{ color: '#94a3b8' }} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search subject name or code..." className="outline-none text-sm flex-1" /><span className="text-xs" style={{ color: '#94a3b8' }}>{visible.length} records</span></div>{error && <div className="m-4 p-3 rounded-xl text-sm" style={{ background: '#fef2f2', color: '#dc2626' }}>{error}</div>}{loading ? <div className="py-20 text-center text-sm" style={{ color: '#94a3b8' }}>Loading subjects...</div> : visible.length === 0 ? <div className="py-20 text-center text-sm" style={{ color: '#94a3b8' }}>No subjects found. Add your first subject.</div> : <table className="w-full"><thead><tr style={{ background: '#f8fafc' }}>{['Subject', 'Code', 'Description', 'Status', 'Actions'].map(label => <th key={label} className="text-left px-5 py-3 text-xs font-bold uppercase" style={{ color: '#94a3b8' }}>{label}</th>)}</tr></thead><tbody>{visible.map(subject => <tr key={subject._id}><td className="px-5 py-4 text-sm font-bold" style={{ borderTop: '1px solid #f1f5f9' }}>{subject.name}</td><td className="px-5 py-4 text-sm" style={{ borderTop: '1px solid #f1f5f9' }}>{subject.code}</td><td className="px-5 py-4 text-sm" style={{ borderTop: '1px solid #f1f5f9', color: '#64748b' }}>{subject.description || 'No description'}</td><td className="px-5 py-4" style={{ borderTop: '1px solid #f1f5f9' }}><span className="px-3 py-1 rounded-full text-xs font-bold" style={{ background: '#ecfdf5', color: '#059669' }}>{subject.status}</span></td><td className="px-5 py-4" style={{ borderTop: '1px solid #f1f5f9' }}><div className="flex gap-2"><button onClick={() => openForm(subject)} className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: '#f1f5f9' }}><Pencil size={15} /></button><button onClick={() => deleteSubject(subject._id)} className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: '#fff1f2', color: '#e11d48' }}><Trash2 size={15} /></button></div></td></tr>)}</tbody></table>}</div>
    {editing !== null && <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: 'rgba(15,23,42,0.55)' }}><form onSubmit={saveSubject} className="bg-white rounded-2xl p-7 w-full max-w-lg"><h3 className="font-bold text-xl mb-6">{editing ? 'Edit Subject' : 'Add Subject'}</h3><div className="grid gap-4"><input required placeholder="Subject name" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} className="px-3 py-3 rounded-xl border-2" style={{ borderColor: '#e2e8f0' }} /><input required placeholder="Subject code" value={form.code} onChange={event => setForm({ ...form, code: event.target.value })} className="px-3 py-3 rounded-xl border-2" style={{ borderColor: '#e2e8f0' }} /><input placeholder="Description" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} className="px-3 py-3 rounded-xl border-2" style={{ borderColor: '#e2e8f0' }} /><select value={form.status} onChange={event => setForm({ ...form, status: event.target.value })} className="px-3 py-3 rounded-xl border-2" style={{ borderColor: '#e2e8f0' }}><option>Active</option><option>Inactive</option></select></div><div className="flex gap-3 mt-6"><button type="button" onClick={() => setEditing(null)} className="flex-1 py-3 rounded-xl" style={{ border: '1px solid #e2e8f0' }}>Cancel</button><button className="flex-1 py-3 rounded-xl text-white font-bold" style={{ background: '#4f46e5' }}>Save Subject</button></div></form></div>}
  </PageLayout>
}
